# Generated by Django 2.2.17 on 2020-11-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_yield',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=-1),
        ),
    ]
